### PR TITLE
Deploy docs

### PR DESCRIPTION
**Pull request by maxbertrand1996**
The documentation is not deployed automatically.

### CODE REVIEW

**Comment by maxbertrand1996** [comment]
Regarding @sloede's suggestion https://github.com/trixi-framework/TrixiBottomTopography.jl/issues/15#issuecomment-1344098649.

**Comment by sloede** [comment]
Just to be clear, you should also try to fix the underlying issues why Documenter produced those warnings 😆

**Comment by maxbertrand1996** [comment]
According to failed `Actions`, the problem is that gh-pages does not have permission to be pushed .
```
Run git push --force origin gh-pages-new:gh-pages
remote: Permission to trixi-framework/TrixiBottomTopography.jl.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/trixi-framework/TrixiBottomTopography.jl/': The requested URL returned error: [4](https://github.com/trixi-framework/TrixiBottomTopography.jl/actions/runs/3636685380/jobs/6161098254#step:4:5)03
Error: Process completed with exit code 128.
```

The documenter.yml seems not to produce any errors.

**Comment by sloede** [comment]
Can you still please try to fix the errors as well: https://github.com/trixi-framework/TrixiBottomTopography.jl/actions/runs/3656445536/jobs/6178898305#step:5:12

**Comment by maxbertrand1996** [comment]
Ok, sorry I did not notice this error. The latest commit should fix it.

**Comment by maxbertrand1996** [comment]
The deployment seems to fail.
```
┌ Info: Deployment criteria for deploying preview build from GitHub Actions:
│ - ✘ ENV["GITHUB_REPOSITORY"]="trixi-framework/TrixiBottomTopography.jl" occurs in repo="https://trixi-framework.github.io/TrixiBottomTopography.jl"
│ - ✔ ENV["GITHUB_REF"] corresponds to a PR number
│ - ✔ PR originates from the same repository
│ - ✔ `push_preview` keyword argument to deploydocs is `true`
│ - ✔ ENV["GITHUB_ACTOR"] exists and is non-empty
│ - ✔ ENV["DOCUMENTER_KEY"] exists and is non-empty
└ Deploying: ✘
```
The latest commit hopefully fixes this

**Comment by maxbertrand1996** [comment]
It seems to work now. 
https://trixi-framework.github.io/TrixiBottomTopography.jl/previews/PR18/
contains all the desired changes.

**Review by sloede — APPROVED** [review]

**Pull request merged**
